[package]
name = "circle-mix"
version = "0.9.54"
description = "CIRCLE MIX desktop and Android application"
authors = ["CIRCLE MIX"]
edition = "2021"

[lib]
name = "circle_mix_lib"
crate-type = ["cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"
