const test=require('node:test'),assert=require('node:assert/strict'),D=require('../src/chart-difficulty');
const C=(notes,bpm=120)=>({bpm,notes}),cuts=(n,step,spread=0)=>C(Array.from({length:n},(_,i)=>({type:'cut',beat:i*step,angle:i*spread%360}))),S=(chart,options)=>D.calculate(chart,options).stars;
function circularFixture({count=28,bpm=185,delta=30,reverseEvery=0,fast=true}){let beat=0,angle=0,direction=1;const notes=[];for(let i=0;i<count;i++){if(reverseEvery&&i&&i%reverseEvery===0)direction*=-1;let step=fast?(i%8<4?.5:.25):(i%8<4?.75:.5);if(i&&i%8===0)step+=1;beat+=step;angle=(angle+delta*direction+360)%360;const slide=i%6===0;notes.push(slide?{type:direction>0?'slideCW':'slideCCW',beat,angle,endAngle:(angle+45*direction+360)%360,durationBeat:step<=.25?.5:1,direction:direction>0?'CW':'CCW'}:{type:'cut',beat,angle});}return {bpm,notes};}
function upperFixture(){const bpm=200,notes=[];let beat=0,angle=0;for(let i=0;i<64;i++){beat+=.5;angle=(angle+45)%360;if(i%16===0)notes.push({type:'traceCW',beat,angle,durationBeat:.75,sweepAngle:270});else if(i%8===0)notes.push({type:'slideCW',beat,angle,durationBeat:.75,sweepAngle:135});else notes.push({type:'cut',beat,angle});if(i%12===0)notes.push({type:'pulse',beat});}return {bpm,notes};}
test('algorithm version and sparse, speed, aim calibration',()=>{assert.equal(D.VERSION,'local-v4');assert.equal(D.MAX_STARS,15);assert.equal(D.signedSweep({type:'traceCW',sweepAngle:1}),1);assert.equal(S(C([])),1);assert.ok(S(cuts(24,1))<S(cuts(24,.2)));const narrow=D.calculate(cuts(24,.3,10)),wide=D.calculate(cuts(24,.3,180));assert.ok(narrow.components.aim<wide.components.aim,`${narrow.components.aim} < ${wide.components.aim}`);});
test('rotation fields and overlap are safely distinguished',()=>{const slow=C([{type:'slideCW',beat:0,angle:0,endAngle:0,durationBeat:8,signedSweepAngle:360}]),fast=C([{type:'slideCW',beat:0,angle:0,endAngle:0,durationBeat:1,signedSweepAngle:360}]),twice=C([{type:'slideCW',beat:0,angle:0,endAngle:0,durationBeat:1,signedSweepAngle:720}]),turns=C([{type:'slideCW',beat:0,angle:0,endAngle:0,durationBeat:1,turns:1}]),zero=C([{type:'slideCW',beat:0,angle:0,endAngle:0,durationBeat:1}]);assert.ok(S(slow)<S(fast)&&S(fast)<S(twice)&&S(zero)<S(fast)&&S(fast)<D.MAX_STARS&&Math.abs(S(fast)-S(turns))<=.2);assert.ok(S(fast)<S(C([...fast.notes,{type:'cut',beat:.5,angle:180}])));});
test('continuous circular chains outrank slower and alternating movement',()=>{const legendary=S(circularFixture({})),extra=S(circularFixture({delta:20,reverseEvery:4,fast:false})),zigzag=S(circularFixture({reverseEvery:1}));assert.ok(legendary>=7.2&&legendary<=8,`legendary ${legendary}`);assert.ok(extra<=legendary-2,`${extra} vs ${legendary}`);assert.ok(zigzag<=legendary-2,`${zigzag} vs ${legendary}`);});
test('parent BPM options affect charts without an embedded bpm',()=>{const chart=circularFixture({});delete chart.bpm;const slow=S(chart,{bpm:120}),fast=S(chart,{bpm:185});assert.ok(fast>=slow+.4,`${slow} -> ${fast}`);});
test('amount and slideAmount preserve full rotations when endpoints match',()=>{const base={type:'slideCW',beat:0,angle:0,endAngle:0,durationBeat:1,direction:'CW'};const amount=S(C([{...base,amount:Math.PI*2}]));const slide=S(C([{...base,slideAmount:Math.PI*2}]));assert.ok(amount>S(C([base])));assert.ok(Math.abs(amount-slide)<=.2);});
test('stars ignore chart padding and repeated song length',()=>{const hard=circularFixture({count:20}),base=S(hard),last=hard.notes.at(-1);const padded={...hard,notes:[...hard.notes,{type:'cut',beat:last.beat+100,angle:last.angle}]};const shifted={...hard,notes:hard.notes.map(note=>({...note,beat:note.beat+100}))};const repeated={...hard,notes:[...hard.notes,...hard.notes.map(note=>({...note,beat:note.beat+40}))]};for(const [name,chart] of [['padded',padded],['shifted',shifted],['repeated',repeated]])assert.ok(Math.abs(S(chart)-base)<=.1,`${name}: ${S(chart)} vs ${base}`);});
test('upper scale extends beyond ten stars without exceeding the display cap',()=>{const stars=S(upperFixture());assert.ok(stars>10,`upper fixture ${stars}`);assert.ok(stars<=D.MAX_STARS,`${stars} <= ${D.MAX_STARS}`);});
test('PULSE adds rhythm burden without fake cursor travel',()=>{const aimedOnly={bpm:120,notes:[{type:'cut',beat:0,angle:0},{type:'cut',beat:1,angle:180}]};const withPulse={bpm:120,notes:[{type:'cut',beat:0,angle:0},{type:'pulse',beat:.5},{type:'cut',beat:1,angle:180}]};const simultaneous={bpm:120,notes:[{type:'cut',beat:0,angle:0},{type:'pulse',beat:0},{type:'cut',beat:1,angle:180}]};const base=D.calculate(aimedOnly),separated=D.calculate(withPulse),chord=D.calculate(simultaneous);assert.equal(D.family({type:'pulse'}),'pulse');assert.equal(separated.components.aim,base.components.aim,'PULSE must not add fake cursor travel');assert.ok(chord.components.pulseOverlap>0,'simultaneous PULSE should add hand-separation burden');});
