const assert=require('assert');
const E=require('../src/cmix-exporter.js'), V=require('../src/cmix-validator.js'), I=require('../src/cmix-importer.js');
(async()=>{
  const input={song:{id:'Test Song!',title:'Test',artist:'Artist',bpm:120,offset:0,packageVersion:1,audioMatch:{durationSeconds:12,durationToleranceSeconds:2,sha256:'a'.repeat(64),suggestedFilename:'test.wav'}},charts:[{descriptor:{id:'Hard Chart',name:'Hard',level:12,style:'CUSTOM',author:'Me'},chart:{schema:'angle-v1',notes:[{type:'traceCW',beat:2,lane:1,endLane:3,durationBeat:1,sweepAngle:90,legacy:true},{type:'cut',beat:1,lane:7,title:'drop'}]}}]};
  const result=await E.createChartPackage(input), repeat=await E.createChartPackage(input);
  assert.equal(result.manifest.id,'test-song'); assert.equal(result.manifest.charts[0].id,'hard-chart'); assert(V.validateManifest(result.manifest).ok); assert(V.validateChart(result.charts[0],{descriptor:result.manifest.charts[0]}).ok); assert.deepEqual([...result.bytes],[...repeat.bytes]); assert.deepEqual(result.entries.map(x=>x.path),['manifest.json','charts/hard-chart.json']); assert.equal(result.charts[0].notes[0].angle,315); assert.equal(result.charts[0].notes[1].signedSweepAngle,90); assert.throws(()=>E.createZip([{path:'../bad',data:'x'}])); assert.throws(()=>E.createZip([{path:'a',data:'x'},{path:'a',data:'x'}]));
  assert.throws(()=>E.normalizeChart({notes:[{type:'trace',beat:0,angle:0,endAngle:0,durationBeat:1}]},{id:'x'})); assert.throws(()=>E.normalizeChart({notes:[{type:'traceCW',beat:0,angle:0,endAngle:90,durationBeat:1,sweepAngle:-90}]},{id:'x'}));
  const file=Object.assign(new Blob([result.bytes]),{name:result.filename}); const inspected=await I.inspect(file); assert(inspected.ok,JSON.stringify(inspected.errors)); assert.equal(inspected.package.manifest.packageType,'chart');
  for(const [ext,data,type] of [['mp3',new Uint8Array([0x49,0x44,0x33,1]),'audio/mpeg'],['ogg',new Uint8Array([79,103,103,83,1]),'audio/ogg'],['wav',new Uint8Array([82,73,70,70,0,0,0,0,87,65,86,69,1]),'audio/wav']]){const audio=Object.assign(new Blob([data],{type}),{name:`audio.${ext}`});const full=await E.createFullPackage({song:{id:`full-${ext}`,title:'Full',artist:'Artist',bpm:120,offset:0,packageVersion:2},audio:{blob:audio,name:audio.name},audioMetadata:{duration:2},charts:input.charts});assert.equal(full.manifest.packageType,'full');assert.equal(full.manifest.audio,`audio.${ext}`);assert.equal(full.manifest.audioMatch,undefined);assert.equal(full.entries.filter(x=>x.path===`audio.${ext}`).length,1);assert.match(full.filename,/full-v2\.cmix$/);const got=await I.inspect(Object.assign(full.blob,{name:full.filename}));assert(got.ok,JSON.stringify(got.errors));assert.deepEqual([...new Uint8Array(await got.package.audioBlob.arrayBuffer())],[...data]);}
  const jacket=Object.assign(new Blob([new Uint8Array([137,80,78,71,1])],{type:'image/png'}),{name:'cover.png'}), audio=Object.assign(new Blob([new Uint8Array([0x49,0x44,0x33,1])],{type:'audio/mpeg'}),{name:'a.mp3'});const full=await E.createFullPackage({song:{id:'multi',title:'Multi',artist:'A',bpm:120,offset:0},audio:{blob:audio,name:'a.mp3'},audioMetadata:{duration:1},jacket:{blob:jacket,name:'cover.png'},charts:[...input.charts,{descriptor:{id:'easy',name:'Easy',level:3,style:'CUSTOM'},chart:{notes:[{type:'cut',beat:1,angle:0}]}}]});const round=await I.inspect(Object.assign(full.blob,{name:full.filename}));assert(round.ok,JSON.stringify(round.errors));assert.deepEqual([...new Uint8Array(await round.package.jacketBlob.arrayBuffer())],[137,80,78,71,1]);assert.deepEqual(full.entries.map(x=>x.path),['manifest.json','audio.mp3','jacket.png','charts/easy.json','charts/hard-chart.json']);assert.equal(await E.crc32Blob(new Blob(['abc']),{chunkSize:1}),E.crc32(new TextEncoder().encode('abc')));await assert.rejects(()=>E.createFullPackage({song:input.song,charts:input.charts,audioMetadata:{duration:1}}));
  console.log('cmix exporter tests passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
