'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

const root=path.resolve(__dirname,'..');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
const tauri=JSON.parse(fs.readFileSync(path.join(root,'src-tauri/tauri.conf.json'),'utf8'));
const cargo=fs.readFileSync(path.join(root,'src-tauri/Cargo.toml'),'utf8');
const rust=fs.readFileSync(path.join(root,'src-tauri/src/lib.rs'),'utf8');
const capability=JSON.parse(fs.readFileSync(path.join(root,'src-tauri/capabilities/default.json'),'utf8'));
const updater=fs.readFileSync(path.join(root,'src/desktop-updater.js'),'utf8');
const releaseConfig=JSON.parse(fs.readFileSync(path.join(root,'src-tauri/tauri.release.conf.json'),'utf8'));
const releaseWorkflow=fs.readFileSync(path.join(root,'.github/workflows/windows-updater-release.yml'),'utf8').replace(/\r\n/g,'\n');
const signingHelper=fs.readFileSync(path.join(root,'scripts/prepare-updater-signing-key.ps1'),'utf8').replace(/\r\n/g,'\n');

assert.equal(tauri.version,'0.9.39');
assert.equal(tauri.app?.withGlobalTauri,true,'desktop updater UI needs the global Tauri core bridge');
assert.equal(tauri.bundle?.createUpdaterArtifacts,false,'normal PR installers must not require the private signing key');
assert.equal(releaseConfig.bundle?.createUpdaterArtifacts,true,'release builds must create signed updater artifacts');
assert.deepEqual(tauri.plugins?.updater?.endpoints,['https://github.com/EpicenterGUY/circle-mix/releases/latest/download/latest.json']);
assert.equal(tauri.plugins?.updater?.windows?.installMode,'passive');
const publicKeyText=Buffer.from(tauri.plugins?.updater?.pubkey||'','base64').toString('utf8');
assert.match(publicKeyText,/^untrusted comment: minisign public key:/);
const publicPayload=Buffer.from(publicKeyText.trim().split(/\r?\n/)[1]||'','base64');
assert.equal(publicPayload.length,42,'minisign public key payload must be Ed + key id + Ed25519 key');
assert.equal(publicPayload.subarray(0,2).toString('ascii'),'Ed');
assert.match(cargo,/tauri-plugin-updater = "2"/);
assert.match(rust,/check_desktop_update/);
assert.match(rust,/install_desktop_update/);
assert.match(rust,/download_and_install/);
assert.match(rust,/app\.restart\(\)/);
assert.ok(capability.permissions.includes('core:default'));
assert.match(updater,/window\.__TAURI__\?\.core\?\.invoke/);
assert.match(updater,/UPDATE CHECK/);
assert.match(updater,/게임과 로컬 데이터에는 영향이 없습니다/);
assert.doesNotMatch(updater,/TAURI_SIGNING_PRIVATE_KEY/);
const privateSecretUses=releaseWorkflow.match(/TAURI_SIGNING_PRIVATE_KEY: \$\{\{ secrets\.TAURI_SIGNING_PRIVATE_KEY \}\}/g)||[];
assert.equal(privateSecretUses.length,1,'the private key secret must only be exposed to the temporary-key preparation step');
assert.match(releaseWorkflow,/TAURI_SIGNING_PRIVATE_KEY_PASSWORD: \$\{\{ secrets\.TAURI_SIGNING_PRIVATE_KEY_PASSWORD \}\}/);
assert.match(releaseWorkflow,/Prepare updater signing key[\s\S]*run: \.\/scripts\/prepare-updater-signing-key\.ps1/);
assert.doesNotMatch(signingHelper,/must contain the complete base64/i,'the helper must not reject Tauri-supported private-key content solely for not being base64');
assert.match(signingHelper,/ToBase64String/,'raw rsign or minisign private-key files must be normalized for Tauri');
assert.match(signingHelper,/local file path/,'a workstation-only key path must produce an actionable GitHub Actions error');
assert.match(signingHelper,/public updater key/,'the helper must reject an accidentally supplied public key');
assert.match(signingHelper,/signer preflight provide the authoritative validation error/,'Tauri must remain the authority for opaque key-content validation');
assert.match(signingHelper,/TAURI_SIGNING_PRIVATE_KEY_PATH=\$keyPath/,'the signing helper must pass a runner-temporary file path to the signer preflight');
assert.match(signingHelper,/TAURI_SIGNING_PRIVATE_KEY=\$keyPath/,'the signing helper must pass the same runner-temporary file path to the release build');
assert.match(signingHelper,/UTF8Encoding\]::new\(\$false\)/,'the signing key file must be written without a UTF-8 BOM');
assert.doesNotMatch(signingHelper,/Write-Host[^\n]*(normalized|secret|decoded|keyMaterial)/i,'the signing helper must never print private key material');
assert.match(releaseWorkflow,/Verify updater signing key[\s\S]*Remove-Item Env:TAURI_SIGNING_PRIVATE_KEY -ErrorAction SilentlyContinue[\s\S]*cargo tauri signer sign --private-key-path \$env:TAURI_SIGNING_PRIVATE_KEY_PATH/,'the explicit signer preflight must clear the inherited build key to avoid passing the same key twice');
assert.match(releaseWorkflow,/signing-preflight\.log/);
assert.match(releaseWorkflow,/windows-updater-build\.log/);
assert.match(releaseWorkflow,/Upload release diagnostics[\s\S]*actions\/upload-artifact@v4/,'release failures must retain safe diagnostics');
assert.match(releaseWorkflow,/circle-mix-windows-updater-release-diagnostics/);
assert.match(releaseWorkflow,/push:\n\s+branches:\n\s+- main\n\s+paths:\n\s+- src-tauri\/tauri\.conf\.json\n\s+- scripts\/prepare-updater-signing-key\.ps1\n\s+- \.github\/workflows\/windows-updater-release\.yml/,'version, signing helper or updater workflow changes must trigger signed updater publication');
assert.match(releaseWorkflow,/permissions:\n\s+contents: write\n\s+issues: write/,'release failures must be allowed to open an observable issue');
assert.match(releaseWorkflow,/gh release view/,'release publication must detect an existing version');
assert.match(releaseWorkflow,/gh release upload[\s\S]*--clobber/,'release publication must replace existing release assets safely');
assert.match(releaseWorkflow,/Create or update GitHub release/,'release publication must be idempotent');
assert.match(releaseWorkflow,/Report release failure/,'release failures must be reported visibly');
assert.match(releaseWorkflow,/Windows updater release failed:/,'failure reports must identify the affected version');
assert.match(releaseWorkflow,/RELEASE_VERSION/,'release metadata must resolve from the committed desktop version');
assert.match(releaseWorkflow,/RELEASE_DRAFT/,'manual draft releases and automatic published releases must share one workflow');
assert.match(releaseWorkflow,/latest\.json/);
assert.match(releaseWorkflow,/windows-x86_64/);
const releaseBuildScript=pkg.scripts?.['desktop:release-build']||'';
assert.match(releaseBuildScript,/^npm run desktop:icons\s+&&\s+cargo tauri build\s+--config\s+src-tauri\/tauri\.release\.conf\.json$/,'signed release builds must generate Tauri icons before using the release configuration');
assert.match(releaseWorkflow,/Build signed NSIS updater[\s\S]*npm run desktop:release-build/,'the signed updater workflow must use the icon-generating release build script');
assert.doesNotMatch(releaseWorkflow,/run: cargo tauri build/,'the signed updater workflow must not duplicate the release build command');
assert.doesNotMatch(releaseWorkflow,/untrusted comment: minisign secret key/,'private signing key must never be committed');

console.log('desktop updater configuration tests passed');
