'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

const root=path.resolve(__dirname,'..');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
const tauri=JSON.parse(fs.readFileSync(path.join(root,'src-tauri/tauri.conf.json'),'utf8'));
const windowsTauri=JSON.parse(fs.readFileSync(path.join(root,'src-tauri/tauri.windows.conf.json'),'utf8'));
const cargo=fs.readFileSync(path.join(root,'src-tauri/Cargo.toml'),'utf8');
const rust=fs.readFileSync(path.join(root,'src-tauri/src/lib.rs'),'utf8');
const cmixImportUi=fs.readFileSync(path.join(root,'src/cmix-import-ui.js'),'utf8');
const workflow=fs.readFileSync(path.join(root,'.github/workflows/windows-desktop.yml'),'utf8');
const prepare=fs.readFileSync(path.join(root,'scripts/prepare-desktop.js'),'utf8');
const settingsPass=fs.readFileSync(path.join(root,'scripts/pc-settings-desktop-pass.js'),'utf8');
const visualPass=fs.readFileSync(path.join(root,'scripts/desktop-visual-pass.js'),'utf8');
const audit=fs.readFileSync(path.join(root,'scripts/audit-desktop-dist.js'),'utf8');

assert.equal(tauri.bundle?.active,true,'desktop bundling must stay enabled');
assert.deepEqual(tauri.bundle?.targets,['nsis'],'Windows v1 must produce only the NSIS installer');
assert.equal(tauri.bundle?.windows?.nsis?.installMode,'currentUser','the test installer must not require administrator privileges');
assert.match(pkg.scripts?.['desktop:build']||'',/cargo tauri build$/,'desktop build must bundle the configured installer');
assert.doesNotMatch(pkg.scripts?.['desktop:build']||'',/--no-bundle/,'desktop build must not suppress installer generation');
assert.match(cargo,new RegExp(`version = "${tauri.version.replaceAll('.','\\.')}"`),'Cargo and Tauri desktop versions must match');
assert.equal(pkg.version,tauri.version,'npm and desktop versions must match for updater releases');
assert.equal(tauri.version,'0.9.54','Windows installer must publish the unlimited-content release');
assert.deepEqual(windowsTauri.bundle?.fileAssociations?.[0]?.ext,['cmix'],'Windows installer must associate .cmix files');
assert.equal(windowsTauri.bundle?.fileAssociations?.[0]?.mimeType,'application/vnd.circle-mix.cmix');
assert.match(cargo,/tauri-plugin-single-instance = "2"/,'desktop must keep one running instance for repeated map opens');
for(const needle of ['PendingCmixPaths','take_desktop_cmix_paths','read_desktop_cmix_file','circlemix-open-cmix','tauri_plugin_single_instance::init'])assert.match(rust,new RegExp(needle.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')),`desktop Rust bridge contains ${needle}`);
for(const needle of ['installDifficultyScroller','installDesktopCmixOpen','take_desktop_cmix_paths','read_desktop_cmix_file','circlemix-open-cmix'])assert.ok(cmixImportUi.includes(needle),`desktop import UI contains ${needle}`);
assert.match(prepare,/replace\(\/\\r\\n\/g,'\\n'\)/,'desktop transforms must normalize Windows CRLF line endings');
assert.match(prepare,/desktop-visual-pass\.js/,'desktop build must retain the dedicated visual pass');
assert.match(prepare,/desktop-updater\.js/,'desktop build must inject the updater UI');
assert.match(prepare,/src\/editor-playtest\.js/,'desktop build must package the editor playtest runtime');
assert.match(prepare,/DESKTOP_UPDATE_LOG_RETRY/,'desktop release metadata must retry the update log after title startup');
assert.match(prepare,/circleMixLastSeenVersion/,'desktop update-log retry must respect the shared last-seen version key');
assert.match(prepare,/safeUpdateLogBtn/,'desktop update-log retry must reuse the existing release-log button');
assert.match(settingsPass,/TRACKPAD_DESKTOP_RELEASE_PATCH/,'final desktop pass must stamp release metadata');
assert.match(settingsPass,/package\.json/,'desktop release version must derive from package metadata');
assert.match(settingsPass,/WINDOWS/,'desktop changelog must announce the Windows release');
assert.match(settingsPass,/CONTENT LIMITS/,'desktop changelog must announce removal of fixed content limits');
assert.match(settingsPass,/DIFFICULTY/,'desktop changelog must announce the higher difficulty range');
assert.match(settingsPass,/SAFETY/,'desktop changelog must explain retained archive safety checks');
assert.match(settingsPass,/maxNotesPerChart/,'desktop release pass must reject a stale note-count ceiling');
assert.match(settingsPass,/DIFFICULTY LIST/,'desktop changelog must retain reachable difficulty-list guidance');
assert.match(settingsPass,/CMIX OPEN/,'desktop changelog must announce .cmix file opening');
assert.match(settingsPass,/더블클릭/,'desktop changelog must explain Explorer double-click opening');
assert.match(settingsPass,/editor-playtest\.js/,'desktop final pass must retain the editor playtest runtime');
for(const asset of ['pc-settings.css','src/pc-settings.js','src/ui.js','trackpad-tablet-area.css','src/trackpad-tablet-area.js','mobile-layout-v2.css','src/mobile-layout-v2.js','song-select-fixes.css','src/editor-playtest.js'])assert.ok(settingsPass.includes(asset),`desktop settings pass includes ${asset}`);
assert.match(visualPass,/readPaletteColor\(game,'pulse'\)/,'desktop visual pass must retain the shared PULSE color');
assert.match(visualPass,/pulseColor===swingCcwColor/,'desktop visual pass must verify PULSE and SWING CCW remain distinct');
assert.match(visualPass,/PULSE_VISUAL_SINGLE_RING/,'PULSE must use the single-ring approach visual');
assert.match(visualPass,/PULSE_HIT_SINGLE_RING/,'PULSE judgement must use a short single-ring burst');
assert.match(visualPass,/SWING_VISUAL_DIRECTIONAL_ARC/,'SWING must use a local directional arc');
assert.match(visualPass,/SWING_HIT_LOCAL_ONLY/,'SWING judgement must stay local');
assert.match(visualPass,/isSwing\?6:14/,'SWING particle count must stay reduced');
assert.match(prepare,/TRACE_PROFILES\.tutorial\.endpointGrace\+\.05/,'desktop tutorial TRACE must keep endpoint grace before finalization');
assert.match(prepare,/remove the SCRATCH tutorial step/,'desktop build must retire new SCRATCH tutorial authoring');
assert.match(prepare,/function checkScratch/,'desktop build must retain legacy SCRATCH playback compatibility');
assert.match(prepare,/DESKTOP · READY/,'desktop offline data must report ready instead of using the web service worker flow');
assert.match(audit,/desktop updater bridge audit failed/,'desktop audit must verify updater command packaging');
assert.match(audit,/desktop update-log retry is missing/,'desktop audit must verify post-title release-log recovery');
assert.match(audit,/desktop trackpad settings or updater entry is missing/,'desktop audit must verify trackpad settings and the updater entry');
assert.match(audit,/song-select overflow fix is missing/,'desktop audit must verify first and last song reachability');
assert.match(audit,/local difficulty sorting is missing/,'desktop audit must verify ascending LOCAL difficulty order');
assert.match(audit,/editor playtest lost sibling difficulty preservation/,'desktop audit must verify sibling difficulty preservation');
assert.match(audit,/desktop POWER forecast model is missing/,'desktop audit must verify the shared POWER model');
assert.match(audit,/\.\/src\/power\.js/,'desktop audit must verify the POWER model is loaded by the desktop index');
assert.match(audit,/PULSE color was not separated from SWING CCW/,'desktop audit must verify PULSE color separation');
assert.match(audit,/PULSE single-ring visual pass is missing/,'desktop audit must verify PULSE simplification');
assert.match(audit,/desktop PULSE multi-aim guide is missing/,'desktop audit must verify simultaneous PULSE aim guidance');
assert.match(audit,/desktop AUTO or large-angle aim flow is missing/,'desktop audit must verify the latest AUTO and mouse aim flow');
assert.match(audit,/SWING directional visual pass is missing/,'desktop audit must verify SWING simplification');
assert.match(audit,/punchier hit-sound pass is missing/,'desktop audit must verify the layered hit-sound pass');
assert.match(audit,/tutorial TRACE finalization still ignores endpoint grace/,'desktop audit must verify TRACE endpoint grace');
assert.match(audit,/desktop tutorial still exposes SCRATCH/,'desktop audit must reject SCRATCH tutorial exposure');
assert.match(audit,/legacy SCRATCH playback compatibility is missing/,'desktop audit must retain legacy SCRATCH playback');
assert.match(audit,/desktop offline-ready shim is missing/,'desktop audit must verify the offline-ready shim');
assert.match(audit,/editor playtest asset is missing/,'desktop audit must verify shared UI and editor runtime packaging');
assert.match(workflow,/\*-setup\.exe/,'Windows CI must locate the NSIS setup executable');
assert.match(workflow,/ArgumentList '\/S'/,'Windows CI must exercise silent NSIS install and uninstall');
assert.match(workflow,/DisplayName -like 'CIRCLE MIX\*'/,'Windows CI must verify the installed application entry');
assert.match(workflow,/InstallLocation\)\.Trim\(\)\.Trim\('\"'\)/,'Windows CI must remove registry quotes before joining the install path');
assert.match(workflow,/UninstallString/,'Windows CI must verify and execute the uninstaller');
assert.match(workflow,/circle-mix-windows-installer-x64/,'Windows CI must publish the installer artifact');

console.log('desktop installer configuration tests passed');
