'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const html=fs.readFileSync('editor.html','utf8');
const ui=fs.readFileSync('src/editor-feasibility.js','utf8');
const css=fs.readFileSync('src/editor.css','utf8');
const songs=fs.readFileSync('src/songs.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');

assert.match(html,/id="physicalCheckBtn"/,'editor must expose a physical-check action');
assert.match(html,/src\/chart-feasibility\.js/,'editor must load the shared feasibility analyzer');
assert.match(html,/src\/editor-feasibility\.js/,'editor must load the feasibility UI bridge');
assert.ok(html.indexOf('src/chart-feasibility.js')<html.indexOf('src/songs.js'),'feasibility analyzer must load before chart tools');
assert.ok(html.indexOf('src/editor.js')<html.indexOf('src/editor-feasibility.js'),'editor runtime must initialize before the UI bridge');
assert.match(ui,/data-feasibility-i/,'physical warning rows must be clickable');
assert.match(ui,/feasibilityTimelineMarker/,'timeline must expose per-note severity markers');
assert.match(ui,/MutationObserver\(decorateRows\)/,'event rows must retain severity after editor rerenders');
assert.match(ui,/경고는 내보내기를 막지 않습니다/,'physical warnings must remain non-blocking');
assert.match(css,/\.feasibilityIssue\.severity-red/);
assert.match(css,/\.noteRow\.severity-orange/);
assert.match(css,/\.feasibilityTimelineMarker\.severity-yellow/);
assert.match(songs,/physical:physical/,'shared chart validation must expose the physical analysis result');
assert.match(sw,/versioned\("\.\/src\/chart-feasibility\.js"\)/,'offline app shell must include the analyzer');
assert.match(sw,/versioned\("\.\/src\/editor-feasibility\.js"\)/,'offline app shell must include the editor bridge');
console.log('editor feasibility integration tests passed');
