"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const http=require("node:http");
const path=require("node:path");
const {chromium}=require("playwright");
const MIME={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json; charset=utf-8",".svg":"image/svg+xml",".png":"image/png",".jpg":"image/jpeg",".webmanifest":"application/manifest+json",".mp3":"audio/mpeg",".wav":"audio/wav"};
function startServer(root){const base=path.resolve(root);const server=http.createServer((req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,"http://127.0.0.1").pathname),relative=pathname==="/"?"editor.html":pathname.replace(/^\/+/,""),file=path.resolve(base,relative);if(file!==base&&!file.startsWith(base+path.sep)){res.writeHead(403);res.end("forbidden");return;}fs.stat(file,(error,stat)=>{if(error||!stat.isFile()){res.writeHead(404);res.end("not found");return;}res.writeHead(200,{"Content-Type":MIME[path.extname(file).toLowerCase()]||"application/octet-stream","Cache-Control":"no-store"});fs.createReadStream(file).pipe(res);});}catch(error){res.writeHead(500);res.end(error.message);}});return new Promise((resolve,reject)=>{server.once("error",reject);server.listen(0,"127.0.0.1",()=>resolve(server));});}
function wav(){const sampleRate=8000,samples=8000,buffer=Buffer.alloc(44+samples*2);buffer.write("RIFF",0);buffer.writeUInt32LE(36+samples*2,4);buffer.write("WAVEfmt ",8);buffer.writeUInt32LE(16,16);buffer.writeUInt16LE(1,20);buffer.writeUInt16LE(1,22);buffer.writeUInt32LE(sampleRate,24);buffer.writeUInt32LE(sampleRate*2,28);buffer.writeUInt16LE(2,32);buffer.writeUInt16LE(16,34);buffer.write("data",36);buffer.writeUInt32LE(samples*2,40);return buffer;}
(async()=>{const server=await startServer(process.cwd()),port=server.address().port;let browser,context,page;try{browser=await chromium.launch({headless:true});context=await browser.newContext({viewport:{width:1440,height:900},serviceWorkers:"block"});page=await context.newPage();const errors=[];page.on("pageerror",e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${port}/editor.html`,{waitUntil:"domcontentloaded"});await page.waitForFunction(()=>window.CircleMixEditorPlaytest&&document.getElementById("playtestBtn"));await page.selectOption("#playtestJudge","LENIENT");await page.evaluate(()=>{for(const [id,value] of [["playtestRing","1.15"],["playtestNoteScale","1.40"],["playtestApproach","1.10"]]){const el=document.getElementById(id);el.value=value;el.dispatchEvent(new Event("input",{bubbles:true}));}});const summary=await page.locator("#playtestSummary").textContent();assert.match(summary,/LENIENT/);assert.match(summary,/1\.15x/);const metrics=await page.evaluate(()=>window.CircleMixEditorPlaytestUI.previewMetrics);assert.equal(Number(metrics.ringRadius.toFixed(1)),225.4);await page.setInputFiles("#audioFile",{name:"playtest.wav",mimeType:"audio/wav",buffer:wav()});await page.locator("#preview").click({position:{x:280,y:60}});await page.waitForFunction(()=>document.querySelectorAll(".noteRow").length===1);await page.locator("#playtestBtn").click();await page.waitForURL(/editorPlaytest=1/,{timeout:20000});await page.waitForFunction(()=>document.body.classList.contains("safeSongSelect")&&document.getElementById("editorPlaytestBadge"),null,{timeout:20000});const active=await page.evaluate(()=>window.CircleMixEditorPlaytestActive);assert.equal(active.judgementPreset,"LENIENT");assert.equal(active.hitRadiusScale,1.15);assert.equal(active.noteScale,1.4);assert.equal(active.approachSeconds,1.1);assert.equal(await page.locator("#editorPlaytestBadge").getAttribute("data-judgement"),"LENIENT");assert.deepEqual(errors,[]);console.log("editor playtest browser test passed");}finally{if(context)await context.close().catch(()=>{});if(browser)await browser.close().catch(()=>{});server.closeAllConnections?.();await new Promise(resolve=>server.close(resolve));}})().catch(error=>{console.error(error);process.exitCode=1;});
