'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const {chromium}=require('playwright');
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.mp3':'audio/mpeg'};
function server(root){const base=path.resolve(root);const app=http.createServer((req,res)=>{const rel=new URL(req.url,'http://127.0.0.1').pathname==='/'?'index.html':decodeURIComponent(new URL(req.url,'http://127.0.0.1').pathname).replace(/^\/+/, '');const file=path.resolve(base,rel);if(file!==base&&!file.startsWith(base+path.sep)){res.writeHead(403);return res.end();}fs.stat(file,(error,stat)=>{if(error||!stat.isFile()){res.writeHead(404);return res.end();}res.writeHead(200,{'Content-Type':MIME[path.extname(file).toLowerCase()]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(file).pipe(res);});});return new Promise((resolve,reject)=>{app.once('error',reject);app.listen(0,'127.0.0.1',()=>resolve(app));});}
async function state(page){return page.evaluate(()=>({width:getComputedStyle(document.documentElement).getPropertyValue('--app-width').trim(),height:getComputedStyle(document.documentElement).getPropertyValue('--app-height').trim(),runtimeStyle:!!document.getElementById('circleMixMobileViewportRuntime'),expanded:document.body.classList.contains('foldExpanded'),landscape:document.body.classList.contains('mobileLandscape'),short:document.body.classList.contains('mobileShortLandscape'),api:!!window.CircleMixPWA?.syncViewport}));}
(async()=>{const app=await server(process.cwd());let browser;try{browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true,deviceScaleFactor:1,serviceWorkers:'block'});const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(`http://127.0.0.1:${app.address().port}/index.html?browserTest=1`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.CircleMixPWA?.syncViewport&&document.getElementById('circleMixMobileViewportRuntime'));await page.waitForFunction(()=>getComputedStyle(document.documentElement).getPropertyValue('--app-width').trim()==='844px');let s=await state(page);assert.equal(s.runtimeStyle,true);assert.equal(s.api,true);assert.equal(s.landscape,true);assert.equal(s.short,true);assert.equal(s.expanded,false);await page.setViewportSize({width:720,height:680});await page.waitForFunction(()=>getComputedStyle(document.documentElement).getPropertyValue('--app-width').trim()==='720px'&&document.body.classList.contains('foldExpanded'));s=await state(page);assert.equal(s.height,'680px');assert.equal(s.landscape,true);assert.equal(s.short,false);assert.equal(s.expanded,true);await page.setViewportSize({width:680,height:720});await page.waitForFunction(()=>getComputedStyle(document.documentElement).getPropertyValue('--app-height').trim()==='720px'&&!document.body.classList.contains('mobileLandscape'));s=await state(page);assert.equal(s.width,'680px');assert.equal(s.expanded,true);assert.equal(s.landscape,false);assert.deepEqual(errors,[]);await context.close();console.log('mobile viewport browser regression passed');}finally{if(browser)await browser.close().catch(()=>{});await new Promise(resolve=>app.close(resolve));}})().catch(error=>{console.error(error);process.exitCode=1;});
