'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const O=require('../src/orbit.js');
assert.deepEqual(O.ORBIT_TYPES,['tap','hold','arc','flipCW','flipCCW','roll','pulse']);
assert.equal(O.judgementForDelta(0.03),'PERFECT');
assert.equal(O.judgementForDelta(0.1),'GREAT');
assert.equal(O.judgementForDelta(0.2),null);
assert.equal(O.inputMatches({type:'tap'},'KeyZ'),true);
assert.equal(O.inputMatches({type:'flipCW'},'ArrowRight'),true);
assert.equal(O.inputMatches({type:'flipCCW'},'ArrowLeft'),true);
assert.equal(O.inputMatches({type:'pulse'},'ShiftLeft'),true);
const chart=O.buildOrbitChart([{type:'tap',beat:0},{type:'flipCCW',beat:2},{type:'tap',beat:4},{type:'flipCW',beat:6},{type:'arc',beat:8,durationBeat:2}]);
assert.equal(chart.length,5);
assert.equal(chart[1].directionAfter,-1);
assert.equal(chart[3].directionAfter,1);
assert.equal(chart[4].duration,2*O.SPB);
const noFlip=O.buildOrbitChart([{type:'tap',beat:0},{type:'tap',beat:2},{type:'tap',beat:4}]);
assert.ok(O.shortestDeg(chart[2].angle,noFlip[2].angle)>0,'flip changes authored path');
const demo=O.makeDemoChart();
for(const type of O.ORBIT_TYPES)assert.ok(demo.some(note=>note.type===type),`demo contains ${type}`);
assert.equal(demo.some(note=>String(note.type).startsWith('trace')),false);
assert.equal(demo.some(note=>String(note.type).startsWith('scratch')),false);
const orbitSource=fs.readFileSync('src/orbit.js','utf8');
assert.doesNotMatch(orbitSource,/coverage\+=dt/,'sustain coverage must not depend on frame rate');
assert.match(orbitSource,/Math\.min\(note\.duration,Math\.max\(0,t-note\.hitTime\)\)/,'sustain coverage uses elapsed gameplay time');
const game=fs.readFileSync('src/game.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
const desktop=fs.readFileSync('scripts/prepare-desktop.js','utf8');
assert.match(game,/safeOrbit/,'title screen exposes ORBIT mode');
assert.match(game,/window\.location\.href="\.\/orbit\.html"/,'ORBIT button opens the standalone mode');
for(const asset of ['./orbit.html','./orbit.css','./src/orbit.js'])assert.ok(sw.includes(asset),`service worker caches ${asset}`);
assert.match(desktop,/orbit\.html/,'desktop packaging includes ORBIT page');
assert.match(desktop,/src\/orbit\.js/,'desktop packaging includes ORBIT runtime');
console.log('orbit mode tests passed');
