'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(root,'src/pc-settings.js'),'utf8');
const css=fs.readFileSync(path.join(root,'pc-settings.css'),'utf8');
const ids=['quickSettingsBtn','settingsBtn','speedDown','speedUp','speedValue','offsetDown','offsetUp','offsetValue','musicDown','musicUp','musicValue','sfxDown','sfxUp','sfxValue','fullToggle','pauseSetPcAim','pauseSetLockedSensitivity','pauseSetAimStabilizer','pauseSetAimVisual','pauseSetVisualResponse','keymapToggle','pauseSetNoteContrast','pauseSetPathBrightness','pauseSetEffectIntensity','pauseSetJudgeGuide','autoToggle','debugToggle','pauseSetUpdateLog','safeOrbit','pauseOverlay','pauseSettingsOverlay'];
function html(){return `<!doctype html><html><head><style>${css}</style></head><body>${ids.map(id=>id.endsWith('Value')?`<span id="${id}">${id==='speedValue'?'0.60s':'50%'}</span>`:`<button id="${id}">${id}</button>`).join('')}<script>window.__clicks={};for(const id of ${JSON.stringify(ids)}){const el=document.getElementById(id);if(el&&el.tagName==='BUTTON')el.addEventListener('click',()=>{window.__clicks[id]=(window.__clicks[id]||0)+1;if(id==='pauseSetPcAim')el.textContent=el.textContent.includes('LOCKED')?'PC AIM AUTO':'PC AIM LOCKED';if(id==='autoToggle'){const on=el.getAttribute('aria-pressed')!=='true';el.setAttribute('aria-pressed',String(on));el.textContent=on?'AUTO ON':'AUTO OFF';}})}</script><script>${js}</script></body></html>`;}
const server=http.createServer((req,res)=>{res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(html());});
(async()=>{let browser;try{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1280,height:800});await page.goto(`http://127.0.0.1:${server.address().port}/?pcSettings=1`);await page.waitForSelector('#pcSettingsHub');assert.equal(await page.locator('#safeOrbit').textContent(),'ORBIT · EXPERIMENTAL');await page.locator('#quickSettingsBtn').click();await page.waitForFunction(()=>!document.getElementById('pcSettingsHub').hidden);assert.equal(await page.locator('.pcSettingsNavButton').count(),6);assert.equal(await page.locator('[data-setting="speed"]').count(),1);assert.equal(await page.locator('[data-setting*="mobile"]').count(),0);await page.locator('[data-setting="pcAim"] .pcSettingAction').click();assert.equal(await page.evaluate(()=>window.__clicks.pauseSetPcAim),1);await page.locator('#pcSettingsSearch').fill('타격음');assert.equal(await page.locator('.pcSettingCard:not([hidden])').count(),1);assert.equal(await page.locator('.pcSettingCard:not([hidden])').getAttribute('data-setting'),'sfx');await page.keyboard.press('Escape');assert.equal(await page.locator('#pcSettingsHub').getAttribute('hidden'),'');console.log('pc settings browser regression passed');}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}})().catch(error=>{console.error(error);process.exitCode=1;});
