(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.CircleMixCmixZip=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
  const enc=new TextEncoder(), dec=new TextDecoder('utf-8',{fatal:true}); let table;
  const issue=(code,path,message)=>({code,path,message}); const u16=(b,o)=>b[o]|b[o+1]<<8, u32=(b,o)=>(b[o]|b[o+1]<<8|b[o+2]<<16|b[o+3]<<24)>>>0;
  function crcUpdate(c,b){if(!table)table=Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0});for(const x of b)c=table[(c^x)&255]^(c>>>8);return c;}
  const crc32=b=>(crcUpdate(0xffffffff,b)^0xffffffff)>>>0;
  const abort=s=>{if(s?.aborted)throw issue('IMPORT_ABORTED','/','Package import was cancelled.');};
  async function read(file,start,end,signal){abort(signal);const x=await file.slice(start,end).arrayBuffer();abort(signal);return new Uint8Array(x);}
  function name(bytes,flags,path){if(!(flags&0x800)&&bytes.some(x=>x>127))throw issue('AMBIGUOUS_FILENAME_ENCODING',path,'Non-ASCII ZIP filenames must declare UTF-8.');try{return dec.decode(bytes)}catch(_){throw issue('INVALID_FILENAME_ENCODING',path,'ZIP filename is not valid UTF-8.');}}
  function extraHasZip64(b){for(let p=0;p+4<=b.length;){const id=u16(b,p),n=u16(b,p+2);if(p+4+n>b.length)throw issue('TRUNCATED_EXTRA_FIELD','/entries','ZIP extra field is truncated.');if(id===1)return true;p+=4+n;}return false;}
  async function parse(file,limits,signal){const size=file.size, tail=await read(file,Math.max(0,size-65557),size,signal), base=Math.max(0,size-65557);let e=-1;
    for(let i=tail.length-22;i>=0;i--)if(u32(tail,i)===0x06054b50&&i+22+u16(tail,i+20)===tail.length){e=i;break;}
    if(e<0)throw issue('TRUNCATED_EOCD','/','ZIP end record is missing, truncated, or has trailing data.'); const eo=base+e;
    if(e>0&&u32(tail,e-4)===0x07064b50||e>0&&u32(tail,e-20)===0x06064b50)throw issue('ZIP64_UNSUPPORTED','/','ZIP64 archives are not supported.');
    const disk=u16(tail,e+4),cdDisk=u16(tail,e+6),onDisk=u16(tail,e+8),count=u16(tail,e+10),cdSize=u32(tail,e+12),cdOff=u32(tail,e+16);
    if([onDisk,count].includes(0xffff)||[cdSize,cdOff].includes(0xffffffff))throw issue('ZIP64_UNSUPPORTED','/','ZIP64 archives are not supported.');
    if(disk||cdDisk||onDisk!==count)throw issue('MULTI_DISK_ZIP','/','Multi-disk ZIP archives are not supported.'); if(count>limits.maxFiles)throw issue('INVALID_ENTRY_COUNT','/entries','ZIP entry count exceeds the package limit.');
    if(cdOff>size||cdSize>size-cdOff)throw issue('CENTRAL_DIRECTORY_BOUNDS','/','Central directory is outside the ZIP file.'); if(cdOff+cdSize!==eo)throw issue('CENTRAL_DIRECTORY_SIZE_MISMATCH','/','Central directory does not end at EOCD.');
    const cd=await read(file,cdOff,eo,signal), out=[], exact=new Set(), folded=new Set(), normalized=new Set(); let p=0,total=0;
    for(let i=0;i<count;i++){abort(signal);if(p+46>cd.length||u32(cd,p)!==0x02014b50)throw issue('TRUNCATED_CENTRAL_DIRECTORY','/entries','Central directory entry is invalid or truncated.');const flags=u16(cd,p+8),method=u16(cd,p+10),crc=u32(cd,p+16),cs=u32(cd,p+20),us=u32(cd,p+24),nl=u16(cd,p+28),xl=u16(cd,p+30),cl=u16(cd,p+32),attrs=u32(cd,p+38),off=u32(cd,p+42),end=p+46+nl+xl+cl;
      if(end>cd.length)throw issue('TRUNCATED_CENTRAL_DIRECTORY','/entries','Central directory variable fields are truncated.');if([cs,us,off].includes(0xffffffff)||extraHasZip64(cd.slice(p+46+nl,p+46+nl+xl)))throw issue('ZIP64_UNSUPPORTED','/entries','ZIP64 entries are not supported.');
      const path=name(cd.slice(p+46,p+46+nl),flags,'/entries'); if(flags&1)throw issue('ENCRYPTED_ZIP',path,'Encrypted ZIP entries are not supported.'); if(flags&8)throw issue('DATA_DESCRIPTOR_UNSUPPORTED',path,'ZIP data descriptors are not supported.'); if(flags&~0x800)throw issue('UNSUPPORTED_ZIP_FLAGS',path,'Unsupported ZIP general-purpose flags.'); if(method!==0&&method!==8)throw issue('UNSUPPORTED_COMPRESSION',path,'Only STORE and DEFLATE entries are supported.'); if(path.endsWith('/'))throw issue('DIRECTORY_ENTRY',path,'Directory entries are not allowed.'); if((attrs>>>16&0xf000)===0xa000)throw issue('SYMLINK_ENTRY',path,'Symlink ZIP entries are not allowed.');
      if(!path||/[\\\x00-\x1f]/.test(path)||path.startsWith('/')||path.split('/').some(x=>x==='.'||x==='..'||!x))throw issue('UNSAFE_PATH',path,'ZIP entry path is unsafe.'); const nfc=path.normalize('NFC'), lower=nfc.toLocaleLowerCase('en-US'); if(exact.has(path))throw issue('DUPLICATE_ENTRY',path,'Duplicate ZIP entry.');if(folded.has(lower))throw issue('CASE_COLLISION',path,'ZIP paths differ only by case.');if(normalized.has(nfc))throw issue('UNICODE_PATH_COLLISION',path,'ZIP paths collide after Unicode normalization.'); exact.add(path);folded.add(lower);normalized.add(nfc);
      if(us>limits.maxUncompressedBytes||cs>limits.maxUncompressedBytes||(us&&(!cs||us/Math.max(cs,1)>limits.maxCompressionRatio))||total+us>limits.maxUncompressedBytes)throw issue('PACKAGE_TOO_LARGE',path,'Declared ZIP entry size exceeds safety limits.');out.push({path,flags,method,crc32:crc,compressedSize:cs,uncompressedSize:us,offset:off,nameBytes:cd.slice(p+46,p+46+nl)});total+=us;p=end;
    } if(p!==cd.length)throw issue('CENTRAL_DIRECTORY_SIZE_MISMATCH','/','Unexpected bytes in central directory.');
    const ranges=[];for(const en of out){const h=await read(file,en.offset,en.offset+30,signal);if(h.length<30||u32(h,0)!==0x04034b50)throw issue('LOCAL_HEADER_MISMATCH',en.path,'Local ZIP header is invalid.');const flags=u16(h,6),method=u16(h,8),crc=u32(h,14),cs=u32(h,18),us=u32(h,22),nl=u16(h,26),xl=u16(h,28),headEnd=en.offset+30+nl+xl;if([cs,us].includes(0xffffffff))throw issue('ZIP64_UNSUPPORTED',en.path,'ZIP64 entries are not supported.');const rest=await read(file,en.offset+30,headEnd,signal);if(extraHasZip64(rest.slice(nl)))throw issue('ZIP64_UNSUPPORTED',en.path,'ZIP64 entries are not supported.');if(flags!==en.flags||method!==en.method||crc!==en.crc32||cs!==en.compressedSize||us!==en.uncompressedSize||rest.slice(0,nl).some((x,i)=>x!==en.nameBytes[i]))throw issue('LOCAL_HEADER_MISMATCH',en.path,'Local and central ZIP metadata differ.');const end=headEnd+cs;if(end>cdOff)throw issue('ENTRY_OUT_OF_BOUNDS',en.path,'ZIP entry overlaps the central directory.');en.dataOffset=headEnd;en.endOffset=end;ranges.push(en);}
    ranges.sort((a,b)=>a.offset-b.offset);let cursor=0;for(const r of ranges){if(r.offset<cursor)throw issue('OVERLAPPING_ENTRIES',r.path,'ZIP local entries overlap.');if(r.offset!==cursor)throw issue(cursor===0?'ZIP_PREAMBLE_NOT_ALLOWED':'UNREFERENCED_ZIP_DATA',r.path,'ZIP contains unreferenced bytes.');cursor=r.endOffset;}if(cursor!==cdOff)throw issue('UNREFERENCED_ZIP_DATA','/','ZIP contains unreferenced data.');return {entries:out,size};
  }
  async function extract(file,en,limit,signal){abort(signal);if(en.uncompressedSize>limit)throw issue('ENTRY_TOO_LARGE',en.path,'Entry exceeds its type safety limit.');const raw=await read(file,en.dataOffset,en.endOffset,signal);let data;if(en.method===0)data=raw;else {if(typeof DecompressionStream==='undefined')throw issue('UNSUPPORTED_COMPRESSION',en.path,'This runtime cannot safely decompress DEFLATE.');const reader=new Blob([raw]).stream().pipeThrough(new DecompressionStream('deflate-raw')).getReader(),chunks=[];let n=0;try{for(;;){abort(signal);const x=await reader.read();if(x.done)break;n+=x.value.byteLength;if(n>en.uncompressedSize||n>limit){await reader.cancel();throw issue('DECOMPRESSION_LIMIT_EXCEEDED',en.path,'DEFLATE output exceeds its declared limit.');}chunks.push(x.value);}}catch(e){if(e?.code)throw e;throw issue('DECOMPRESSION_FAILED',en.path,'DEFLATE decompression failed.');}data=new Uint8Array(n);let p=0;for(const x of chunks)data.set(x,p),p+=x.length;}if(data.length!==en.uncompressedSize)throw issue('SIZE_MISMATCH',en.path,'Extracted size does not match ZIP metadata.');if(crc32(data)!==en.crc32)throw issue('CRC_MISMATCH',en.path,'ZIP entry CRC-32 does not match its data.');return data;}
  return Object.freeze({parse,extract,crc32,crcUpdate,issue});
});
