/* Transactional LOCAL SONGS library.  Kept dependency-free for browser and Node tests. */
(function(root,factory){const api=factory(root);if(typeof module==='object')module.exports=api;root.CircleMixLocalLibrary=api;})(typeof window!=='undefined'?window:globalThis,function(root){
  'use strict';
  const DB_NAME='circle-mix-local-songs', VERSION=3, SONGS='songs', AUDIO='builtinAudio', BACKUPS='songBackups', META='libraryMeta', encoder=new TextEncoder();
  const instance=`${Date.now()}-${Math.random().toString(36).slice(2)}`; let dbPromise,cache=[],cacheState='stale',listeners=new Set(),busy=new Set();
  const err=(code,message,extra={})=>Object.assign(new Error(message),{code,...extra});
  const blobBytes=v=>v instanceof Blob?v.size:0;
  function estimateRecordBytes(record){ const copy={...record,audioBlob:null,jacketBlob:null,jacketData:null}; return blobBytes(record?.audioBlob)+blobBytes(record?.jacketBlob)+encoder.encode(JSON.stringify(copy)).byteLength+1024; }
  function fingerprint(r){return r?JSON.stringify([r.id,r.updatedAt||null,r.packageVersion||null,r.packageHash||null]):null;}
  function validateStoredRecord(r){const issues=[]; if(!r||typeof r!=='object')issues.push('record missing'); else {if(!r.id||typeof r.id!=='string')issues.push('id missing');if(r.source!=='local')issues.push('source must be local');if(!r.title||!r.artist)issues.push('title or artist missing');if(!(Number(r.bpm)>0))issues.push('invalid bpm');if(!r.audioBlob||typeof r.audioBlob.size!=='number')issues.push('audio Blob missing');if(!r.charts||typeof r.charts!=='object')issues.push('charts missing');if(!r.difficulties||typeof r.difficulties!=='object')issues.push('difficulties missing');for(const id of Object.keys(r.difficulties||{})){if(!r.charts?.[id])issues.push(`difficulty ${id} has no chart`);else if(!Array.isArray(r.charts[id].notes)||!r.charts[id].notes.length)issues.push(`chart ${id} is empty`);}if(!r.updatedAt||Number.isNaN(Date.parse(r.updatedAt)))issues.push('invalid updatedAt');if(r.packageType==='full'&&!r.audioBlob)issues.push('FULL audio missing');if(r.packageType==='chart'&&(!r.linkedAudio||!r.localAudioFileName))issues.push('CHART audio link metadata missing');} return {ok:!issues.length,issues,status:issues.length?'broken':'healthy'};}
  function open(){if(dbPromise)return dbPromise;if(!root.indexedDB)return Promise.reject(err('STORAGE_ACCESS_FAILED','IndexedDB is unavailable.'));dbPromise=new Promise((resolve,reject)=>{const r=root.indexedDB.open(DB_NAME,VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(SONGS))d.createObjectStore(SONGS,{keyPath:'id'});if(!d.objectStoreNames.contains(AUDIO))d.createObjectStore(AUDIO,{keyPath:'id'});if(!d.objectStoreNames.contains(BACKUPS))d.createObjectStore(BACKUPS,{keyPath:'id'});if(!d.objectStoreNames.contains(META))d.createObjectStore(META,{keyPath:'key'});};r.onblocked=()=>reject(err('STORAGE_ACCESS_FAILED','Local library upgrade is blocked. Close or refresh other CIRCLE MIX tabs.'));r.onerror=()=>reject(err('STORAGE_ACCESS_FAILED',r.error?.message||'Cannot open local library.'));r.onsuccess=()=>{const d=r.result;d.onversionchange=()=>d.close();resolve(d);};});return dbPromise;}
  function request(req){return new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
  async function transaction(stores,fn){const db=await open();return new Promise((resolve,reject)=>{let value;const tx=db.transaction(stores,'readwrite');tx.onabort=()=>reject(normalize(tx.error));tx.onerror=()=>{};try{value=fn(tx);}catch(e){tx.abort();reject(e);return;}tx.oncomplete=()=>resolve(value);});}
  function normalize(e){if(e?.code)return e;const name=e?.name||'';return /quota/i.test(name)||e?.code===22?err('QUOTA_EXCEEDED','Browser storage quota was exceeded.'):err('STORAGE_ACCESS_FAILED',e?.message||'Local library transaction failed.');}
  async function list(){cacheState='loading';try{const db=await open(),rows=await new Promise((resolve,reject)=>{const r=db.transaction(SONGS).objectStore(SONGS).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error);});cache=rows;cacheState='ready';return rows.slice().sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''));}catch(e){cacheState='unavailable';throw normalize(e);}}
  async function get(id){const db=await open();return request(db.transaction(SONGS).objectStore(SONGS).get(id));}
  async function getStorageStatus(){const local=cache.reduce((n,r)=>n+estimateRecordBytes(r),0);if(!root.navigator?.storage?.estimate)return {available:false,localBytes:local,persistent:null};try{const x=await root.navigator.storage.estimate(),persistent=root.navigator.storage.persisted?await root.navigator.storage.persisted():null;return {available:true,usage:x.usage,quota:x.quota,remaining:Math.max(0,(x.quota||0)-(x.usage||0)),persistent,localBytes:local};}catch(e){return {available:false,localBytes:local,error:'STORAGE_ESTIMATE_UNAVAILABLE'};}}
  function notify(type,id){const event={type,id,instance};listeners.forEach(f=>f(event));channel?.postMessage(event);}
  const channel=typeof root.BroadcastChannel==='function'?new root.BroadcastChannel('circle-mix-local-library'):null;channel?.addEventListener('message',async e=>{if(!e.data||e.data.instance===instance)return;try{await list();listeners.forEach(f=>f({...e.data,remote:true}));}catch(_) {}});
  async function install(record,options={}){const valid=validateStoredRecord(record);if(!valid.ok)throw err('INVALID_RECORD',valid.issues.join('; '));if(busy.has(record.id))throw err('INSTALL_IN_PROGRESS','This song is already being installed.');busy.add(record.id);try{const status=await getStorageStatus(),existing=await get(record.id),backup=existing&&options.keepBackup!==false?estimateRecordBytes(existing):0,growth=estimateRecordBytes(record)+backup-(existing?estimateRecordBytes(existing):0);if(status.available&&status.remaining<growth+1024*128)throw err('INSUFFICIENT_STORAGE_ESTIMATE','Estimated browser storage is insufficient.',{required:growth,remaining:status.remaining});const expected=options.expectedCurrent;if(expected&&fingerprint(existing)!==fingerprint(expected.exists?expected:null))throw err('STALE_INSTALL_CONFLICT','The stored song changed while confirmation was open.',{current:existing});await transaction([SONGS,BACKUPS,META],tx=>{const songs=tx.objectStore(SONGS),backups=tx.objectStore(BACKUPS);const r=songs.get(record.id);r.onsuccess=()=>{const current=r.result;if(expected&&fingerprint(current)!==fingerprint(expected.exists?expected:null)){tx.abort();return;}if(current&&options.keepBackup!==false)backups.put({id:record.id,record:current,backedUpAt:new Date().toISOString(),replacedByVersion:record.packageVersion||null,estimatedBytes:estimateRecordBytes(current)});songs.put(record);tx.objectStore(META).put({key:'schema',version:VERSION,updatedAt:new Date().toISOString()});};});const saved=await get(record.id);if(fingerprint(saved)!==fingerprint(record))throw err('READ_BACK_MISMATCH','Saved record could not be verified.');await list();notify(existing?'updated':'installed',record.id);return {record:saved,previous:existing,backupBytes:backup};}finally{busy.delete(record.id);}}
  async function remove(id,{withBackup=false}={}){await transaction(withBackup?[SONGS,BACKUPS]:[SONGS],tx=>{tx.objectStore(SONGS).delete(id);if(withBackup)tx.objectStore(BACKUPS).delete(id);});await list();notify('deleted',id);}
  async function restorePrevious(id){await transaction([SONGS,BACKUPS],tx=>{const s=tx.objectStore(SONGS),b=tx.objectStore(BACKUPS),a=s.get(id),x=b.get(id);x.onsuccess=()=>{a.onsuccess=()=>{if(!a.result||!x.result?.record){tx.abort();return;}s.put(x.result.record);b.put({id,record:a.result,backedUpAt:new Date().toISOString(),estimatedBytes:estimateRecordBytes(a.result)});};};});const saved=await get(id);if(!saved)throw err('READ_BACK_MISMATCH','Restored record is missing.');await list();notify('restored',id);return saved;}
  async function scanIntegrity(){const rows=await list(),db=await open(),backups=await new Promise((resolve,reject)=>{const r=db.transaction(BACKUPS).objectStore(BACKUPS).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error);}),items=rows.map(record=>({...validateStoredRecord(record),id:record.id,estimatedBytes:estimateRecordBytes(record)}));for(const b of backups)if(!rows.some(r=>r.id===b.id))items.push({id:b.id,status:'warning',issues:['orphan backup'],estimatedBytes:b.estimatedBytes||0});return {items,healthy:items.filter(x=>x.status==='healthy').length,broken:items.filter(x=>x.status==='broken').length,warning:items.filter(x=>x.status==='warning').length,totalBytes:items.reduce((n,x)=>n+x.estimatedBytes,0)};}
  return {DB_NAME,VERSION,open,list,get,install,remove,restorePrevious,estimateRecordBytes,getStorageStatus,validateStoredRecord,scanIntegrity,subscribe(f){listeners.add(f);return()=>listeners.delete(f);},cached:()=>cache.slice(),cacheState:()=>cacheState,normalizeError:normalize,requestPersistent:async()=>root.navigator?.storage?.persist?root.navigator.storage.persist():false};
});
